### ISSUE TITLE
Some apps are "immune" to tiling

### ISSUE THREAD

**Issue by mriehl** [nathankot/mjolnir.tiling#16]
Hi,

Thanks for your work on this, I'm coming from archlinux with i3 and being able to add tiling logic to OSX is really a lifesaver :-)

There are some (very few) apps that seem to be totally "immune" to tiling - they keep floating around. `togglefloat()` also has no effect on them.

The biggest offender currently seems to be the HipChat app.
Are you aware about this? I'm guessing it's a problem with the app, not with mjolnir.tiling - but maybe there's something I can do to make it work? I'm able to move the app window around and resize it using `grid.set` which feels kinda strange.
Apologies if the answer is obvious, I'm new to OSX and have no clue how the accessibility / windowing works under the hood.

**Comment by csaunders** [comment]
Does the Hip Chat app chrome have a title in it? I believe this is also the case with Slack as well.

**Comment by mriehl** [comment]
@csaunders Yes, there's a title.

**Comment by csaunders** [comment]
[This is probably where the offending code is](https://github.com/nathankot/mjolnir.tiling/blob/109664dc44fa596620b5a10a6ee14dd199bf4133/tiling.lua#L87-L97). The `iswindowincluded` filter could be causing something weird to happen or incorrectly.

Taking a quick look it would appear that windows which are in the `mainscreen` might be excluded from the filter. Is the problem being replicated on a single display or are you using multiple displays?

**Comment by mriehl** [comment]
I'm experiencing this with a single display. Would you like me to try it with a multi-display setup?

**Comment by csaunders** [comment]
Nah, I'm just trying to get as much information possible so I can help replicate it locally. You've said it's happening on other applications. Could you list them? Turns out Slack updated their client so it's working properly now.

**Comment by mriehl** [comment]
I think I have it figured out (the code you linked helped).
Calling `window:title()` on the hipchat window shows that the window has no title (albeit having a title in the UI).

**Comment by terinjokes** [comment]
I'm also having this problem with HipChat. HipChat's OSX app has a stylized chrome, so while it might have a title from a UI perspective, I wouldn't be surprised if it didn't actually have one.

(Aside: Amusing, on my linux machine I have one application that doesn't play nicely with my window manager, qtile. You guessed it, HipChat)

**Comment by terinjokes** [comment]
Using SIMBL, I set a title on the HipChat's `MainWindow` instance, which allowed it to be tiled properly.

```objective-c
[[[NSApplication sharedApplication] mainWindow] setTitle:@"HipChat"]
```

**Comment by nathankot** [comment]
Hmmm I think it may be worthwhile exploring an alternative to the title check solution used for hidden windows like Adobe creative cloud

--
Nathan Kot

**Comment by gerardo** [comment]
I'm not sure if this is the same problem, but borderless windows apps line [iterm2-borderless](https://github.com/Nasga/iterm2-borderless) are also inmune to tiling

**Comment by nathankot** [comment]
@gerardo yup, I have experienced this, in the end I just run iterm2 with borders :P

Side note, the nightly build of iterm2 now has borderless support so you don't need to use that patch anymore.

**Comment by gerardo** [comment]
@nathankot Oh, nice one. Will check the nightly build. Thanks!
